name: Daily Kasa Telegram Report

on:
  schedule:
    - cron: "30 18 * * *"

  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  send-report:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Checkbox report
        env:
          CHECKBOX_LICENSE_KEY: ${{ secrets.CHECKBOX_LICENSE_KEY }}
          CHECKBOX_PIN: ${{ secrets.CHECKBOX_PIN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          CHECKBOX_CLIENT_NAME: roman-kasa-report
          CHECKBOX_CLIENT_VERSION: 1.0.0
        run: |
          python main2.py